import React from 'react';
import './page1.css';
import logo1 from "../img/logo1.png";
import Footer from '../Admin/footer';
const CoursesPage2 = () => {
    return (
        <div>
            <nav className="navbar">
                <div className="logo">
                    <img src={logo1} alt="Logo" style={{ height: '100px' }} />
                    <h2 className="Ed">EduH</h2>
                </div>
                <div className="nav-link">
                    <a href="/AdminDashboard">Home</a>
                    <a href="/CoursesPage">Courses</a>
                    <a href="/StudentDetails">Student Details</a>
                    <a href="/InstitutionDetails">Institutions</a>
                    <button className="logout-btn" onClick={() => window.location.href = '/'}>Logout</button>
                </div>
            </nav>
            <div className="course-content">
            <h1 className="course-title">Week 2: Intermediate Techniques</h1>
            <div className="course-item">
                <h2 className="topic-title">Day 4: Advanced Prompts</h2>
                <p className="topic-content">Learn to craft more complex prompts to get better and more specific results from DALL-E.</p>
            </div>
            <div className="course-item">
                <h2 className="topic-title">Day 5: Image Refinement</h2>
                <p className="topic-content">Techniques for refining and enhancing the images generated by DALL-E.</p>
            </div>
            <div className="course-item">
                <h2 className="topic-title">Day 6: Use Cases</h2>
                <p className="topic-content">Explore various use cases of DALL-E in different industries and scenarios.</p>
            </div>
            <button className="nav-button" onClick={() => window.location.href = '/CoursesPage3'}>Next</button>
        </div>
        <Footer/>
            </div>
    );
};

export default CoursesPage2;
